def clean_prompt(cv_text):
    return f"""
TU ES UN EXPERT EN RESTRUCTURATION DE DONNÉES. TON BUT EST DE REMETTRE CE CV EN ORDRE DE MANIÈRE LOGIQUE ET LINÉAIRE 
DANS SON INTEGRALITE.

TEXTE DU CV :
{cv_text}
"""
